CREATE TABLE PRODUCT_CATEGORIES(
  CATEGORY_ID INT PRIMARY KEY,
  CATEGORY_NAME VARCHAR2(100) NOT NULL
);

CREATE TABLE PRODUCTS(
  PRODUCT_ID INT PRIMARY KEY,
  PRODUCT_NAME VARCHAR2(100) NOT NULL,
  SKU VARCHAR2(100) NOT NULL,
  IMAGE VARCHAR2(100),
  PRICE NUMBER(10,2) NOT NULL,
  DESCRIPTION VARCHAR2(100),
  CATEGORY_ID INT NOT NULL,
  CONSTRAINT U_SKU UNIQUE (SKU),
  CONSTRAINT FK_PRODUCT_CAT FOREIGN KEY (CATEGORY_ID) REFERENCES PRODUCT_CATEGORIES(CATEGORY_ID)
);

COMMIT;